package com.docmind.common.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Builder;

import java.time.Instant;
import java.util.List;

/**
 * Response DTO returned after a successful RAG query.
 *
 * Includes:
 * - The generated answer (from GPT-4o-mini)
 * - Whether the answer passed the validation step (Ollama Mistral)
 * - The source document chunks used to ground the answer
 * - Metadata: model used, latency, retry count (for observability)
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Builder
public record QueryResponse(

        /** The grounded, context-aware answer generated by the primary LLM. */
        String answer,

        /** True = Mistral validation passed; False = answer exceeded retry limit, returned with disclaimer. */
        boolean validated,

        /** Optional disclaimer appended when max retries are exhausted. */
        String disclaimer,

        /** Source document chunks used to ground the answer. */
        List<SourceChunk> sources,

        /** The LLM model that generated the answer. */
        String modelUsed,

        /** Total pipeline latency in milliseconds. */
        long latencyMs,

        /** Number of retrieve-generate cycles before a valid answer was produced. */
        int retryCount,

        /** Timestamp when the response was generated. */
        Instant generatedAt
) {
    /**
     * A source chunk — a reference to a document fragment used for grounding the answer.
     *
     * @param documentId   The ID of the parent document.
     * @param sourceTag    Optional tag (e.g., filename, topic) for display.
     * @param content      The actual text chunk used as context.
     * @param score        Cosine similarity score (0.0–1.0) from the vector search.
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record SourceChunk(
            String documentId,
            String sourceTag,
            String content,
            double score
    ) {}
}
